"""empty message

Revision ID: 0d9b86d4755b
Revises: 3bb8fbd8cd2d
Create Date: 2023-01-12 09:29:40.665700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9b86d4755b'
down_revision = '3bb8fbd8cd2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.drop_column('cajas')

    with op.batch_alter_table('tabla_rechazos', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_rechazos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cajas', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
