"""empty message

Revision ID: 61771f3430ae
Revises: 0d9b86d4755b
Create Date: 2023-01-12 09:30:16.093816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61771f3430ae'
down_revision = '0d9b86d4755b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cajas', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.drop_column('cajas')

    # ### end Alembic commands ###
